language: java
jdk:
   - openjdk11
cache:
   directories:
      - "$HOME/.m2/repository"
      - "$HOME/.sonar/cache"

# Do integration test on configured servers.
env:
   - SERVER=wildfly-hibernate
#  - SERVER=glassfish-eclipselink
#  - SERVER=payara-eclipselink
script: mvn verify -Dmaven.javadoc.skip=true -P $SERVER

# Do snapshot deployment.
deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   skip_cleanup: true
   on:
      branch: jakartified
      condition: "$SERVER = wildfly-hibernate"
